#!/usr/bin/env python3
"""Generate Rust and Python transport facts from schemas/transport.toml."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import tomllib


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "schemas" / "transport.toml"
RUST_OUTPUT = ROOT / "crates/platform/transport/src/generated_spec.rs"
PYTHON_OUTPUT = ROOT / "kairospy/infrastructure/transport/generated_spec.py"


def load() -> tuple[dict[str, object], str]:
    raw = MANIFEST.read_bytes()
    spec = tomllib.loads(raw.decode())
    canonical = json.dumps(spec, sort_keys=True, separators=(",", ":")).encode()
    return spec, hashlib.sha256(canonical).hexdigest()


def render_rust(spec: dict[str, object], fingerprint: str) -> str:
    streams = spec["streams"]
    assert isinstance(streams, dict)
    constants = "\n".join(
        f"    pub const {name.upper()}: i32 = {value};"
        for name, value in streams.items()
    )
    return f'''// @generated by scripts/generate/generate_transport_spec.py; do not edit.
pub const TRANSPORT_SPEC_VERSION: u32 = {spec["version"]};
pub const TRANSPORT_FINGERPRINT: &str =
    "{fingerprint}";
pub const DEFAULT_CHANNEL: &str = {json.dumps(spec["default_channel"])};
pub const DEFAULT_MAX_PAYLOAD_LEN: usize = {spec["max_payload_len"]};

pub mod stream_ids {{
{constants}
}}
'''


def render_python(spec: dict[str, object], fingerprint: str) -> str:
    streams = spec["streams"]
    assert isinstance(streams, dict)
    constants = "\n".join(
        f"{name.upper()} = {value}" for name, value in streams.items()
    )
    return f'''# @generated by scripts/generate/generate_transport_spec.py; do not edit.
TRANSPORT_SPEC_VERSION = {spec["version"]}
TRANSPORT_FINGERPRINT = "{fingerprint}"
DEFAULT_CHANNEL = {json.dumps(spec["default_channel"])}
DEFAULT_MAX_PAYLOAD_LEN = {spec["max_payload_len"]}

{constants}
'''


def update(path: Path, content: str, *, check: bool) -> bool:
    if path.exists() and path.read_text() == content:
        return True
    if check:
        print(f"stale generated transport spec: {path.relative_to(ROOT)}")
        return False
    path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec, fingerprint = load()
    valid = update(RUST_OUTPUT, render_rust(spec, fingerprint), check=args.check)
    valid &= update(PYTHON_OUTPUT, render_python(spec, fingerprint), check=args.check)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
