from __future__ import annotations

from pathlib import Path


def add_run_commands(commands) -> None:
    run_product = commands.add_parser("run", help="run strategy code from a Workspace across backtest, simulation, paper or live")
    run_actions = run_product.add_subparsers(dest="action", required=True)
    run_start = run_actions.add_parser("start", help="start a reusable RunConfig")
    run_start.add_argument("--config", required=True, type=Path, help="RunConfig TOML path, for example configs/runs/backtest.toml")
    run_start.add_argument("--param", action="append", default=[], help="strategy parameter key=value; repeatable")
    run_start.add_argument("--confirm-live", action="store_true", help="required explicit confirmation for live runs")
    run_start.add_argument(
        "--supervise-live-services",
        action="store_true",
        help="for live runs, start configured live market services under the runtime supervisor",
    )
    run_config = run_actions.add_parser("config", help="validate or explain reusable RunConfig files")
    run_config_actions = run_config.add_subparsers(dest="config_action", required=True)
    run_config_validate = run_config_actions.add_parser("validate", help="validate a RunConfig TOML file")
    run_config_validate.add_argument("path", type=Path)
    run_config_validate.add_argument("--strict", action="store_true")
    run_config_explain = run_config_actions.add_parser("explain", help="show the resolved RunConfig launch intent")
    run_config_explain.add_argument("path", type=Path)
    run_live = run_actions.add_parser("live", help="operate a named long-lived live run")
    run_live.add_argument(
        "live_action",
        choices=(
            "start", "recover", "status", "attach", "stop", "pause", "resume", "reduce-only", "clear-reduce-only",
            "cancel-all", "reconcile", "commands", "kill-switch", "reset-kill-switch", "reload-risk-limits",
            "target-position", "streams", "spaces", "incidents", "close-incident", "metrics", "export", "force-stop",
        ),
        nargs="?",
        default="status",
    )
    run_live.add_argument("subscription_action", nargs="?", choices=("show", "add", "remove", "set"))
    run_live.add_argument("subscription_values", nargs="*", help="stream or space IDs for run live streams/spaces add/remove/set")
    run_live.add_argument("--run-id", required=True, help="unique run instance id")
    run_live.add_argument("--config", type=Path, help="RunConfig TOML path for start/recover")
    run_live.add_argument("--param", action="append", default=[], help="strategy parameter key=value; repeatable")
    run_live.add_argument("--confirm-live", action="store_true", help="required explicit confirmation for live start/recover")
    run_live.add_argument("--foreground", action="store_true", help="run the live daemon in this CLI process")
    run_live.add_argument("--duration-seconds", type=float, help="bounded foreground run duration; implies --foreground")
    run_live.add_argument("--poll-seconds", type=float, default=0.25, help="foreground daemon stop-request poll interval")
    run_live.add_argument("--log-file", type=Path, help="background daemon log file; defaults under .kairos/runtime/live/<run-id>")
    run_live.add_argument("--stale-after-seconds", type=float, default=5.0, help="heartbeat age before live status is stale")
    run_live.add_argument("--fresh", action="store_true", help="request a fresh daemon status snapshot before reading status")
    run_live.add_argument("--wait", type=float, default=0.0, help="seconds to wait for --fresh command acknowledgement")
    run_live.add_argument("--interval-seconds", type=float, default=1.0, help="attach status/log poll interval")
    run_live.add_argument("--tail-lines", type=int, default=80, help="attach log lines to show before following")
    run_live.add_argument("--no-follow", action="store_true", help="attach once, print the current snapshot, and exit")
    run_live.add_argument("--reason", help="operator reason for stop requests")
    run_live.add_argument("--actor", default="cli", help="operator actor for control commands")
    run_live.add_argument("--timeout-seconds", type=float, help="graceful stop timeout before force handling")
    run_live.add_argument("--force", action="store_true", help="force stop after graceful stop timeout")
    run_live.add_argument("--reconciliation-evidence", help="required evidence reference for reset-kill-switch")
    run_live.add_argument("--risk-limits-hash", help="limits hash for reload-risk-limits")
    run_live.add_argument(
        "--leg",
        action="append",
        default=[],
        help="target position leg as venue,product,instrument,side,quantity; repeat for paired trades",
    )
    run_live.add_argument("--intent-id", help="optional operator intent id for target-position")
    run_live.add_argument("--idempotency-key", help="optional operator command idempotency key")
    run_live.add_argument("--output", type=Path, help="metrics/export artifact path for metrics or export actions")
    run_live.add_argument("--prometheus", action="store_true", help="render metrics as Prometheus text format")
    run_status = run_actions.add_parser("status", help="inspect a run instance status")
    run_status.add_argument("--run-id", required=True)
    run_status.add_argument("--stale-after-seconds", type=float, default=5.0, help="heartbeat age before live status is stale")
    run_status.add_argument("--fresh", action="store_true", help="request a fresh daemon status snapshot before reading status")
    run_status.add_argument("--wait", type=float, default=0.0, help="seconds to wait for --fresh command acknowledgement")
    run_stop = run_actions.add_parser("stop", help="request a run instance to stop")
    run_stop.add_argument("--run-id", required=True)
    run_stop.add_argument("--reason", help="operator reason for stop requests")
    run_stop.add_argument("--actor", default="cli", help="operator actor for control commands")
    run_stop.add_argument("--timeout-seconds", type=float)
    run_stop.add_argument("--force", action="store_true")
    run_force_stop = run_actions.add_parser("force-stop", help="force stop a run after a short graceful timeout")
    run_force_stop.add_argument("--run-id", required=True)
    run_force_stop.add_argument("--reason", required=True)
    run_force_stop.add_argument("--actor", default="cli")
    run_force_stop.add_argument("--timeout-seconds", type=float, default=1.0)
    run_pause = run_actions.add_parser("pause", help="pause new non-reducing orders for a run")
    run_pause.add_argument("--run-id", required=True)
    run_pause.add_argument("--reason", required=True)
    run_pause.add_argument("--actor", default="cli")
    run_resume = run_actions.add_parser("resume", help="resume new orders for a paused run")
    run_resume.add_argument("--run-id", required=True)
    run_resume.add_argument("--reason", required=True)
    run_resume.add_argument("--actor", default="cli")
    run_reduce = run_actions.add_parser("reduce-only", help="put a run into reduce-only mode")
    run_reduce.add_argument("--run-id", required=True)
    run_reduce.add_argument("--reason", required=True)
    run_reduce.add_argument("--actor", default="cli")
    run_clear_reduce = run_actions.add_parser("clear-reduce-only", help="clear reduce-only mode for a run")
    run_clear_reduce.add_argument("--run-id", required=True)
    run_clear_reduce.add_argument("--reason", required=True)
    run_clear_reduce.add_argument("--actor", default="cli")
    run_cancel_all = run_actions.add_parser("cancel-all", help="request cancellation of all working orders for a run")
    run_cancel_all.add_argument("--run-id", required=True)
    run_cancel_all.add_argument("--reason", required=True)
    run_cancel_all.add_argument("--actor", default="cli")
    run_reconcile = run_actions.add_parser("reconcile", help="request a reconciliation snapshot for a run")
    run_reconcile.add_argument("--run-id", required=True)
    run_reconcile.add_argument("--reason", default="operator reconciliation requested")
    run_reconcile.add_argument("--actor", default="cli")
    run_commands = run_actions.add_parser("commands", help="list recent operator commands for a run")
    run_commands.add_argument("--run-id", required=True)
    run_commands.add_argument("--limit", type=int, default=20)
    run_incidents = run_actions.add_parser("incidents", help="list runtime incidents for a run")
    run_incidents.add_argument("--run-id", required=True)
    run_incidents.add_argument("--status", choices=("open", "closed", "all"), default="open")
    run_incidents.add_argument("--limit", type=int, default=20)
    run_close_incident = run_actions.add_parser("close-incident", help="close a runtime incident")
    run_close_incident.add_argument("--run-id", required=True)
    run_close_incident.add_argument("--incident-id", required=True)
    run_close_incident.add_argument("--reason", required=True)
    run_close_incident.add_argument("--actor", default="cli")
    run_metrics = run_actions.add_parser("metrics", help="show runtime metrics for a run")
    run_metrics.add_argument("--run-id", required=True)
    run_metrics.add_argument("--stale-after-seconds", type=float, default=5.0)
    run_metrics.add_argument("--output", type=Path, help="write metrics artifact to this path")
    run_metrics.add_argument("--prometheus", action="store_true", help="render metrics as Prometheus text format")
    run_export = run_actions.add_parser("export", help="export runtime control-plane artifacts for a run")
    run_export.add_argument("--run-id", required=True)
    run_export.add_argument("--output", type=Path)
    run_export.add_argument("--stale-after-seconds", type=float, default=5.0)
    run_inspect = run_actions.add_parser("inspect"); run_inspect.add_argument("--db", type=Path)
    run_inspect.add_argument("--artifact",type=Path);run_inspect.add_argument("--at")
    run_inspect.add_argument("--run-id")
    target_run_replay = run_actions.add_parser("replay", help="replay a Run workspace from its snapshot")
    target_run_replay.add_argument("--run-id", required=True)
    target_run_compare = run_actions.add_parser("compare", help="compare two Run workspaces")
    target_run_compare.add_argument("--first", required=True)
    target_run_compare.add_argument("--second", required=True)
