// @generated by scripts/generate/generate_transport_spec.py; do not edit.
pub const TRANSPORT_SPEC_VERSION: u32 = 1;
pub const TRANSPORT_FINGERPRINT: &str =
    "ff2376afeb51db8bf217d2bcc2b81396460c9b92cd1ae3d8891fadf6c43389c4";
pub const DEFAULT_CHANNEL: &str = "aeron:udp?endpoint=localhost:40123";
pub const DEFAULT_MAX_PAYLOAD_LEN: usize = 67108864;

pub mod stream_ids {
    pub const REFERENCE_CHANGES: i32 = 1201;
    pub const MARKET_EVENTS: i32 = 1301;
    pub const ACCOUNT_EVENTS: i32 = 1401;
    pub const EXECUTION_EVENTS: i32 = 1501;
    pub const RISK_EVENTS: i32 = 1601;
    pub const CAPITAL_EVENTS: i32 = 1701;
}
