// @generated by scripts/generate/generate_transport_spec.py; do not edit.
pub const TRANSPORT_SPEC_VERSION: u32 = 1;
pub const TRANSPORT_FINGERPRINT: &str =
    "57b5fa156ebc110aca6fb65562d65eb493849510aa9a7dad9e167f864c057641";
pub const DEFAULT_CHANNEL: &str = "aeron:udp?endpoint=localhost:40123";
pub const DEFAULT_MAX_PAYLOAD_LEN: usize = 67108864;

pub mod stream_ids {
    pub const REFERENCE_CHANGES: i32 = 1201;
    pub const MARKET_EVENTS: i32 = 1301;
    pub const ACCOUNT_EVENTS: i32 = 1401;
    pub const EXECUTION_EVENTS: i32 = 1501;
    pub const RISK_EVENTS: i32 = 1601;
}
