include "common.fbs";
include "../../common/decimal.fbs";

namespace kairos.reference.v2;

table FinancialProduct {
  product_id:string (required);
  product_type:string (required);
  name:string (required);
  asset_id:string (required);
  provider_product_id:string (required);
  provider_id:string;
  issuer_id:string;
  currency_asset_id:string;
  min_amount:kairos.common.v2.Decimal64;
  max_amount:kairos.common.v2.Decimal64;
  apr:kairos.common.v2.Decimal64;
  lock_period_days:int;
  maturity_at_unix_nanos:ulong;
  status:ReferenceLifecycleStatus = UNSPECIFIED;
  effective_from_unix_nanos:ulong;
  effective_to_unix_nanos:ulong;
}
