"""Project starter assets owned by the Workspace application boundary."""

from __future__ import annotations

import json
from pathlib import Path

from .domain import Workspace


BACKTEST_TEMPLATE = "backtest"
SUPPORTED_PROJECT_TEMPLATES = frozenset({BACKTEST_TEMPLATE})


def validate_project_template(template: str | None) -> str | None:
    if template is None:
        return None
    value = template.strip().lower()
    if value not in SUPPORTED_PROJECT_TEMPLATES:
        supported = ", ".join(sorted(SUPPORTED_PROJECT_TEMPLATES))
        raise ValueError(
            f"unknown project template {template!r}; choose one of: {supported}"
        )
    return value


def project_template_paths(project: Path, template: str | None) -> tuple[Path, ...]:
    if validate_project_template(template) != BACKTEST_TEMPLATE:
        return ()
    return (
        project / "kairos_demo",
        project / "KAIROS_QUICKSTART.md",
    )


def install_project_template(
    workspace: Workspace, template: str | None
) -> tuple[Path, ...]:
    if validate_project_template(template) != BACKTEST_TEMPLATE:
        return ()

    project = workspace.paths.project_root
    strategy_package = project / "kairos_demo"
    account = workspace.paths.root / "accounts" / "demo-paper.toml"
    events = workspace.paths.data_root() / "examples" / "demo-market.jsonl"
    launch = workspace.paths.launch_config("demo-backtest")
    guide = project / "KAIROS_QUICKSTART.md"
    targets = (strategy_package, account, events, launch, guide)
    conflicts = [path for path in targets if path.exists()]
    if conflicts:
        joined = ", ".join(str(path) for path in conflicts)
        raise FileExistsError(
            f"project template would overwrite existing files: {joined}"
        )

    strategy_package.mkdir(parents=True, exist_ok=False)
    (strategy_package / "__init__.py").write_text(
        '"""Kairos generated example strategy package."""\n', encoding="utf-8"
    )
    (strategy_package / "strategy.py").write_text(_BACKTEST_STRATEGY, encoding="utf-8")

    account.parent.mkdir(parents=True, exist_ok=True)
    account.write_text(_BACKTEST_ACCOUNT, encoding="utf-8")

    events.parent.mkdir(parents=True, exist_ok=True)
    events.write_text(
        "".join(json.dumps(event, separators=(",", ":")) + "\n" for event in _events()),
        encoding="utf-8",
    )

    launch.parent.mkdir(parents=True, exist_ok=True)
    launch.write_text(_BACKTEST_LAUNCH, encoding="utf-8")

    guide.write_text(_BACKTEST_GUIDE, encoding="utf-8")
    return (strategy_package / "strategy.py", account, events, launch, guide)


def _events() -> tuple[dict[str, object], ...]:
    base = 1_704_067_200_000_000_000
    closes = ("42000", "42100", "42350", "42200", "42500")
    return tuple(
        {
            "Bar": {
                "market_id": "market:binance:spot:BTCUSDT",
                "instrument_id": "instrument:binance:spot:BTCUSDT",
                "timeframe": "1m",
                "open": {"mantissa": int(close), "scale": 0},
                "high": {"mantissa": int(close) + 50, "scale": 0},
                "low": {"mantissa": int(close) - 50, "scale": 0},
                "close": {"mantissa": int(close), "scale": 0},
                "volume": {"mantissa": 10, "scale": 0},
                "observed_at_unix_nanos": base + index * 60_000_000_000,
                "source_id": "kairos-demo",
                "derivation": "provider",
            }
        }
        for index, close in enumerate(closes)
    )


_BACKTEST_STRATEGY = '''from __future__ import annotations

from kairospy.strategy import StrategyBase


class DemoBacktest(StrategyBase):
    """Small deterministic strategy generated by ``project init``."""

    strategy_id = "demo-backtest"

    def on_start(self, context):
        context.state["bars"] = 0
        context.subscribe(
            "BTCUSDT",
            selectors=("bar",),
            exchange="binance",
            market_type="spot",
            asset_type="crypto",
        )

    def on_data(self, context, event):
        if event.kind != "bar":
            return
        bars = int(context.state.get("bars", 0)) + 1
        context.state["bars"] = bars
        if bars == 1:
            context.target_position(
                "instrument:binance:spot:BTCUSDT",
                "0.01",
                account="demo-paper",
                reason="enter the generated demo position",
            )
        elif bars == 5:
            context.target_position(
                "instrument:binance:spot:BTCUSDT",
                "0",
                account="demo-paper",
                reason="close the generated demo position",
            )
'''

_BACKTEST_ACCOUNT = """[account]
id = "demo-paper"
broker = "paper"
environment = "paper"
default_segment = "spot"
fee_rate = "0.001"

[initial_balances]
USDT = "100000"

[segments.spot]
product_family = "spot"
"""

_BACKTEST_LAUNCH = """[launch]
id = "demo-backtest"
mode = "backtest"
strategy = "kairos_demo.strategy:DemoBacktest"

[account]
ref = "demo-paper"

[execution]
dry_run = true

[backtest]
data_root = "data"
storage_format = "jsonl"

[backtest.market]
start = "2024-01-01T00:00:00Z"
end = "2024-01-02T00:00:00Z"
events = "data/examples/demo-market.jsonl"
scope = "instance"
"""

_BACKTEST_GUIDE = """# Kairos backtest quickstart

This project includes an offline, deterministic example. No exchange credentials
or network connection are required.

```bash
kairos launch diagnose validate demo-backtest
kairos launch start demo-backtest
kairos launch wait demo-backtest
```

Edit `kairos_demo/strategy.py`, then start another run to experiment. Use
`kairos launch report demo-backtest` to read the latest completed report and
`kairos project doctor` when a command cannot proceed.
"""
