from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol, TypeVar


T = TypeVar("T")


class ConnectionFactory(Protocol[T]):
    def create_connection(self) -> T | None: ...


class ConnectionManager(Protocol):
    def register(self, key: str, resource: object, *, role: str = "resource") -> object: ...
    def resolve(self, key: str, *, role: str, factory: ConnectionFactory[object]) -> object | None: ...
    def get(self, key: str) -> object | None: ...
    def remove(self, key: str) -> object | None: ...
    def start_roles(self, roles: tuple[str, ...]) -> None: ...
    def stop_roles(self, roles: tuple[str, ...]) -> None: ...
    def reconnect(self, key: str | None = None) -> object | None: ...
    def health(self) -> Mapping[str, object]: ...


__all__ = ["ConnectionFactory", "ConnectionManager"]
