include "../../common/v2/metadata.fbs";
include "types.fbs";

namespace kairos.risk.v2;

table AuthorizeAndReserveRequest {
  request_id:string (required);
  reservation_id:string (required);
  account_id:string (required);
  strategy_id:string (required);
  instrument_id:string (required);
  exchange_id:string;
  usages:[RiskUsage] (required);
  reservation_ttl_nanos:ulong;
  context:RiskContext (required);
}

table AuthorizeAndReserveCommand {
  metadata:kairos.common.v2.CommandMetadata (required);
  request:AuthorizeAndReserveRequest (required);
}

root_type AuthorizeAndReserveCommand;
file_identifier "RAV2";
