version = 1
default_channel = "aeron:udp?endpoint=localhost:40123"
max_payload_len = 67108864

[streams]
reference_changes = 1201
market_events = 1301
account_events = 1401
execution_events = 1501
risk_events = 1601
capital_events = 1701
